module.exports = {
  extends: ['stylelint-config-standard-scss'],
  plugins: ['stylelint-order'],
  customSyntax: 'postcss-scss',
  rules: {
    'order/order': [
      'custom-properties',
      'dollar-variables',
      'declarations',
      'rules',
      'at-rules'
    ],
    'order/properties-order': [
      'display',
      'position',
      'inset',
      'top',
      'right',
      'bottom',
      'left',
      'z-index',
      'flex',
      'flex-grow',
      'flex-shrink',
      'flex-basis',
      'flex-direction',
      'flex-wrap',
      'justify-content',
      'align-items',
      'align-content',
      'gap',
      'grid',
      'grid-template-columns',
      'grid-template-rows',
      'grid-column',
      'grid-row',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'padding',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
      'margin',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'border',
      'border-radius',
      'background',
      'color',
      'font',
      'font-family',
      'font-size',
      'font-weight',
      'line-height',
      'text-align',
      'text-transform',
      'letter-spacing',
      'box-shadow',
      'transition',
      'transform',
      'opacity',
      'overflow'
    ],
    'selector-class-pattern': null,
    'no-descending-specificity': null
  }
}
