--
-- PostgreSQL database dump
--

\restrict QAgMWCbgeFZ93kxpihsb4YODaSQXUBgqIhT2MBeuRMobT1rGeJa9TImz17zv9Ur

-- Dumped from database version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)
-- Dumped by pg_dump version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: dim_estimate; Type: TABLE; Schema: public; Owner: dima_admin
--

CREATE TABLE public.dim_estimate (
    estimate_id bigint CONSTRAINT type_of_smeta_id_smeta_not_null NOT NULL,
    estimate_name text
);


ALTER TABLE public.dim_estimate OWNER TO dima_admin;

--
-- Name: TABLE dim_estimate; Type: COMMENT; Schema: public; Owner: dima_admin
--

COMMENT ON TABLE public.dim_estimate IS 'the table with estmates names';


--
-- Name: type_of_smeta_id_smeta_seq; Type: SEQUENCE; Schema: public; Owner: dima_admin
--

ALTER TABLE public.dim_estimate ALTER COLUMN estimate_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_of_smeta_id_smeta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dim_estimate type_of_smeta_pkey; Type: CONSTRAINT; Schema: public; Owner: dima_admin
--

ALTER TABLE ONLY public.dim_estimate
    ADD CONSTRAINT type_of_smeta_pkey PRIMARY KEY (estimate_id);


--
-- Name: TABLE dim_estimate; Type: ACL; Schema: public; Owner: dima_admin
--

GRANT SELECT ON TABLE public.dim_estimate TO app_turnover_u4s;
GRANT ALL ON TABLE public.dim_estimate TO app_mad_podolsk;
GRANT SELECT ON TABLE public.dim_estimate TO metabase;


--
-- Name: SEQUENCE type_of_smeta_id_smeta_seq; Type: ACL; Schema: public; Owner: dima_admin
--

GRANT SELECT ON SEQUENCE public.type_of_smeta_id_smeta_seq TO app_turnover_u4s;
GRANT ALL ON SEQUENCE public.type_of_smeta_id_smeta_seq TO app_mad_podolsk;
GRANT SELECT,USAGE ON SEQUENCE public.type_of_smeta_id_smeta_seq TO metabase;


--
-- PostgreSQL database dump complete
--

\unrestrict QAgMWCbgeFZ93kxpihsb4YODaSQXUBgqIhT2MBeuRMobT1rGeJa9TImz17zv9Ur

