--
-- PostgreSQL database dump
--

\restrict UtMUx0ujgIA4cQodNA67FZdplss0XYoW8ygY9mbBnfe3HCXOPukCgT54FTBOUK4

-- Dumped from database version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)
-- Dumped by pg_dump version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: dim_work_status; Type: TABLE; Schema: public; Owner: dima_admin
--

CREATE TABLE public.dim_work_status (
    work_status_id bigint CONSTRAINT status_of_work_id_status_not_null NOT NULL,
    work_status_name text
);


ALTER TABLE public.dim_work_status OWNER TO dima_admin;

--
-- Name: TABLE dim_work_status; Type: COMMENT; Schema: public; Owner: dima_admin
--

COMMENT ON TABLE public.dim_work_status IS 'the table with types of status for each done work';


--
-- Name: status_of_work_id_status_seq; Type: SEQUENCE; Schema: public; Owner: dima_admin
--

ALTER TABLE public.dim_work_status ALTER COLUMN work_status_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.status_of_work_id_status_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dim_work_status status_of_work_pkey; Type: CONSTRAINT; Schema: public; Owner: dima_admin
--

ALTER TABLE ONLY public.dim_work_status
    ADD CONSTRAINT status_of_work_pkey PRIMARY KEY (work_status_id);


--
-- Name: TABLE dim_work_status; Type: ACL; Schema: public; Owner: dima_admin
--

GRANT SELECT ON TABLE public.dim_work_status TO app_turnover_u4s;
GRANT ALL ON TABLE public.dim_work_status TO app_mad_podolsk;
GRANT SELECT ON TABLE public.dim_work_status TO metabase;


--
-- Name: SEQUENCE status_of_work_id_status_seq; Type: ACL; Schema: public; Owner: dima_admin
--

GRANT SELECT ON SEQUENCE public.status_of_work_id_status_seq TO app_turnover_u4s;
GRANT ALL ON SEQUENCE public.status_of_work_id_status_seq TO app_mad_podolsk;
GRANT SELECT,USAGE ON SEQUENCE public.status_of_work_id_status_seq TO metabase;


--
-- PostgreSQL database dump complete
--

\unrestrict UtMUx0ujgIA4cQodNA67FZdplss0XYoW8ygY9mbBnfe3HCXOPukCgT54FTBOUK4

