--
-- PostgreSQL database dump
--

\restrict 7EdiCjZdJpPd3bUpDImswVKtlW8O1aBgoVh0gHVojTxMG7fRBCW3uQ0ndpAvHxL

-- Dumped from database version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)
-- Dumped by pg_dump version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: dim_road_section; Type: TABLE; Schema: public; Owner: dima_admin
--

CREATE TABLE public.dim_road_section (
    road_section_id bigint CONSTRAINT section_of_road_id_section_of_road_not_null NOT NULL,
    road_section_name text,
    road_category text,
    length_km numeric,
    width_m numeric,
    area_m2 numeric,
    registry_number text,
    passport_volume numeric,
    sidewalk_passport_volume numeric
);


ALTER TABLE public.dim_road_section OWNER TO dima_admin;

--
-- Name: TABLE dim_road_section; Type: COMMENT; Schema: public; Owner: dima_admin
--

COMMENT ON TABLE public.dim_road_section IS 'the table with names and details of road sections';


--
-- Name: COLUMN dim_road_section.passport_volume; Type: COMMENT; Schema: public; Owner: dima_admin
--

COMMENT ON COLUMN public.dim_road_section.passport_volume IS 'Паспортный объем участка дороги';


--
-- Name: section_of_road_id_section_of_road_seq; Type: SEQUENCE; Schema: public; Owner: dima_admin
--

ALTER TABLE public.dim_road_section ALTER COLUMN road_section_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.section_of_road_id_section_of_road_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dim_road_section section_of_road_pkey; Type: CONSTRAINT; Schema: public; Owner: dima_admin
--

ALTER TABLE ONLY public.dim_road_section
    ADD CONSTRAINT section_of_road_pkey PRIMARY KEY (road_section_id);


--
-- Name: TABLE dim_road_section; Type: ACL; Schema: public; Owner: dima_admin
--

GRANT SELECT ON TABLE public.dim_road_section TO app_turnover_u4s;
GRANT ALL ON TABLE public.dim_road_section TO app_mad_podolsk;
GRANT SELECT ON TABLE public.dim_road_section TO metabase;


--
-- Name: SEQUENCE section_of_road_id_section_of_road_seq; Type: ACL; Schema: public; Owner: dima_admin
--

GRANT SELECT ON SEQUENCE public.section_of_road_id_section_of_road_seq TO app_turnover_u4s;
GRANT ALL ON SEQUENCE public.section_of_road_id_section_of_road_seq TO app_mad_podolsk;
GRANT SELECT,USAGE ON SEQUENCE public.section_of_road_id_section_of_road_seq TO metabase;


--
-- PostgreSQL database dump complete
--

\unrestrict 7EdiCjZdJpPd3bUpDImswVKtlW8O1aBgoVh0gHVojTxMG7fRBCW3uQ0ndpAvHxL

