--
-- PostgreSQL database dump
--

\restrict vZb2QjjPZtC8QRt8uXK9OuR5wWaeJ7nGhlm2zHcRYkVOLjKHRHNixnqct2HYeCg

-- Dumped from database version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)
-- Dumped by pg_dump version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: dim_estimate_section; Type: TABLE; Schema: public; Owner: dima_admin
--

CREATE TABLE public.dim_estimate_section (
    estimate_section_id bigint CONSTRAINT smeta_section_id_smeta_section_not_null NOT NULL,
    estimate_section_name text,
    estimate_id bigint
);


ALTER TABLE public.dim_estimate_section OWNER TO dima_admin;

--
-- Name: smeta_section_id_smeta_section_seq; Type: SEQUENCE; Schema: public; Owner: dima_admin
--

ALTER TABLE public.dim_estimate_section ALTER COLUMN estimate_section_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.smeta_section_id_smeta_section_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dim_estimate_section smeta_section_pkey; Type: CONSTRAINT; Schema: public; Owner: dima_admin
--

ALTER TABLE ONLY public.dim_estimate_section
    ADD CONSTRAINT smeta_section_pkey PRIMARY KEY (estimate_section_id);


--
-- Name: dim_estimate_section fk_smeta_section_type; Type: FK CONSTRAINT; Schema: public; Owner: dima_admin
--

ALTER TABLE ONLY public.dim_estimate_section
    ADD CONSTRAINT fk_smeta_section_type FOREIGN KEY (estimate_id) REFERENCES public.dim_estimate(estimate_id);


--
-- Name: TABLE dim_estimate_section; Type: ACL; Schema: public; Owner: dima_admin
--

GRANT SELECT ON TABLE public.dim_estimate_section TO app_turnover_u4s;
GRANT ALL ON TABLE public.dim_estimate_section TO app_mad_podolsk;
GRANT SELECT ON TABLE public.dim_estimate_section TO metabase;


--
-- Name: SEQUENCE smeta_section_id_smeta_section_seq; Type: ACL; Schema: public; Owner: dima_admin
--

GRANT SELECT ON SEQUENCE public.smeta_section_id_smeta_section_seq TO app_turnover_u4s;
GRANT ALL ON SEQUENCE public.smeta_section_id_smeta_section_seq TO app_mad_podolsk;
GRANT SELECT,USAGE ON SEQUENCE public.smeta_section_id_smeta_section_seq TO metabase;


--
-- PostgreSQL database dump complete
--

\unrestrict vZb2QjjPZtC8QRt8uXK9OuR5wWaeJ7nGhlm2zHcRYkVOLjKHRHNixnqct2HYeCg

