--
-- PostgreSQL database dump
--

\restrict IVZFrOz1FSUPQ64szx5zjVDwgLwijqUWqhYreslQhgva35EfEd6KQMDeBUAjHKV

-- Dumped from database version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)
-- Dumped by pg_dump version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: dim_unit; Type: TABLE; Schema: public; Owner: dima_admin
--

CREATE TABLE public.dim_unit (
    unit_id bigint CONSTRAINT unit_list_id_unit_not_null NOT NULL,
    unit_name text
);


ALTER TABLE public.dim_unit OWNER TO dima_admin;

--
-- Name: TABLE dim_unit; Type: COMMENT; Schema: public; Owner: dima_admin
--

COMMENT ON TABLE public.dim_unit IS 'the table with unit names';


--
-- Name: unit_list_id_unit_seq; Type: SEQUENCE; Schema: public; Owner: dima_admin
--

ALTER TABLE public.dim_unit ALTER COLUMN unit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unit_list_id_unit_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dim_unit unit_list_pkey; Type: CONSTRAINT; Schema: public; Owner: dima_admin
--

ALTER TABLE ONLY public.dim_unit
    ADD CONSTRAINT unit_list_pkey PRIMARY KEY (unit_id);


--
-- Name: TABLE dim_unit; Type: ACL; Schema: public; Owner: dima_admin
--

GRANT SELECT ON TABLE public.dim_unit TO app_turnover_u4s;
GRANT ALL ON TABLE public.dim_unit TO app_mad_podolsk;
GRANT SELECT ON TABLE public.dim_unit TO metabase;


--
-- Name: SEQUENCE unit_list_id_unit_seq; Type: ACL; Schema: public; Owner: dima_admin
--

GRANT SELECT ON SEQUENCE public.unit_list_id_unit_seq TO app_turnover_u4s;
GRANT ALL ON SEQUENCE public.unit_list_id_unit_seq TO app_mad_podolsk;
GRANT SELECT,USAGE ON SEQUENCE public.unit_list_id_unit_seq TO metabase;


--
-- PostgreSQL database dump complete
--

\unrestrict IVZFrOz1FSUPQ64szx5zjVDwgLwijqUWqhYreslQhgva35EfEd6KQMDeBUAjHKV

