--
-- PostgreSQL database dump
--

\restrict XNR480mEhH6U41GiDYIggTCfGEY0BBFNNzTwKNAtVfyFJ7oKyVyF2eAenWbjzjP

-- Dumped from database version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)
-- Dumped by pg_dump version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: initial_data; Type: SCHEMA; Schema: -; Owner: dima_admin
--

CREATE SCHEMA initial_data;


ALTER SCHEMA initial_data OWNER TO dima_admin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: fact_price_2025; Type: TABLE; Schema: initial_data; Owner: dima_admin
--

CREATE TABLE initial_data.fact_price_2025 (
    estimate_id bigint CONSTRAINT prices_2025_id_smeta_not_null NOT NULL,
    estimate_section_id bigint CONSTRAINT prices_2025_id_smeta_section_not_null NOT NULL,
    work_item_id bigint CONSTRAINT prices_2025_id_description_not_null NOT NULL,
    unit_price numeric CONSTRAINT prices_2025_price_not_null NOT NULL,
    price_id bigint CONSTRAINT prices_2025_id_price_not_null NOT NULL
);


ALTER TABLE initial_data.fact_price_2025 OWNER TO dima_admin;

--
-- Name: fact_price_2026_upto_may; Type: TABLE; Schema: initial_data; Owner: dima_admin
--

CREATE TABLE initial_data.fact_price_2026_upto_may (
    price_id bigint CONSTRAINT prices_2026_uptomay_id_price_not_null NOT NULL,
    estimate_id bigint,
    estimate_section_id bigint,
    work_item_id bigint,
    unit_price numeric
);


ALTER TABLE initial_data.fact_price_2026_upto_may OWNER TO dima_admin;

--
-- Name: fact_work_actual_pik; Type: TABLE; Schema: initial_data; Owner: dima_admin
--

CREATE TABLE initial_data.fact_work_actual_pik (
    work_date date,
    estimate_name text,
    estimate_section_name text,
    work_name text,
    quantity_done numeric,
    status text
);


ALTER TABLE initial_data.fact_work_actual_pik OWNER TO dima_admin;

--
-- Name: fact_work_by_subcontractor; Type: TABLE; Schema: initial_data; Owner: dima_admin
--

CREATE TABLE initial_data.fact_work_by_subcontractor (
    work_report_id bigint NOT NULL
);


ALTER TABLE initial_data.fact_work_by_subcontractor OWNER TO dima_admin;

--
-- Name: fact_work_plan_monthly; Type: TABLE; Schema: initial_data; Owner: app_mad_podolsk
--

CREATE TABLE initial_data.fact_work_plan_monthly (
    month_start_date date CONSTRAINT skpdi_plan_agg_month_start_not_null NOT NULL,
    work_name text CONSTRAINT skpdi_plan_agg_description_not_null NOT NULL,
    unit text CONSTRAINT skpdi_plan_agg_unit_not_null NOT NULL,
    quantity_planned numeric CONSTRAINT skpdi_plan_agg_planned_volume_not_null NOT NULL,
    source_files text,
    loaded_at timestamp with time zone DEFAULT now() CONSTRAINT skpdi_plan_agg_loaded_at_not_null NOT NULL
);


ALTER TABLE initial_data.fact_work_plan_monthly OWNER TO app_mad_podolsk;

--
-- Name: fact_work_skpdi_report; Type: TABLE; Schema: initial_data; Owner: dima_admin
--

CREATE TABLE initial_data.fact_work_skpdi_report (
    plan_row_id numeric(20,0),
    work_report_id numeric(20,0) CONSTRAINT skpdi_report_raw_id_done_work_not_null NOT NULL,
    work_date date,
    close_time time without time zone,
    work_status_id bigint,
    road_section_id bigint,
    work_item_id bigint,
    quantity_done numeric,
    comment_text text,
    work_name text
);


ALTER TABLE initial_data.fact_work_skpdi_report OWNER TO dima_admin;

--
-- Name: prices_2025_id_price_seq; Type: SEQUENCE; Schema: initial_data; Owner: dima_admin
--

CREATE SEQUENCE initial_data.prices_2025_id_price_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE initial_data.prices_2025_id_price_seq OWNER TO dima_admin;

--
-- Name: prices_2025_id_price_seq; Type: SEQUENCE OWNED BY; Schema: initial_data; Owner: dima_admin
--

ALTER SEQUENCE initial_data.prices_2025_id_price_seq OWNED BY initial_data.fact_price_2025.price_id;


--
-- Name: prices_2026_uptomay_id_price_seq; Type: SEQUENCE; Schema: initial_data; Owner: dima_admin
--

ALTER TABLE initial_data.fact_price_2026_upto_may ALTER COLUMN price_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME initial_data.prices_2026_uptomay_id_price_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: skpdi_report_raw_tmp; Type: TABLE; Schema: initial_data; Owner: dima_admin
--

CREATE TABLE initial_data.skpdi_report_raw_tmp (
    plan_row_id numeric(20,0),
    work_report_id numeric(20,0),
    work_date date,
    close_time time without time zone,
    work_status_name text,
    road_section_name text,
    work_name text,
    quantity_done numeric,
    comment_text text
);


ALTER TABLE initial_data.skpdi_report_raw_tmp OWNER TO dima_admin;

--
-- Name: fact_price_2025 price_id; Type: DEFAULT; Schema: initial_data; Owner: dima_admin
--

ALTER TABLE ONLY initial_data.fact_price_2025 ALTER COLUMN price_id SET DEFAULT nextval('initial_data.prices_2025_id_price_seq'::regclass);


--
-- Name: fact_work_by_subcontractor fact_work_by_subcontractor_pkey; Type: CONSTRAINT; Schema: initial_data; Owner: dima_admin
--

ALTER TABLE ONLY initial_data.fact_work_by_subcontractor
    ADD CONSTRAINT fact_work_by_subcontractor_pkey PRIMARY KEY (work_report_id);


--
-- Name: fact_price_2025 prices_2025_pkey; Type: CONSTRAINT; Schema: initial_data; Owner: dima_admin
--

ALTER TABLE ONLY initial_data.fact_price_2025
    ADD CONSTRAINT prices_2025_pkey PRIMARY KEY (price_id);


--
-- Name: fact_price_2026_upto_may prices_2026_uptomay_pkey; Type: CONSTRAINT; Schema: initial_data; Owner: dima_admin
--

ALTER TABLE ONLY initial_data.fact_price_2026_upto_may
    ADD CONSTRAINT prices_2026_uptomay_pkey PRIMARY KEY (price_id);


--
-- Name: fact_work_plan_monthly skpdi_plan_agg_pkey; Type: CONSTRAINT; Schema: initial_data; Owner: app_mad_podolsk
--

ALTER TABLE ONLY initial_data.fact_work_plan_monthly
    ADD CONSTRAINT skpdi_plan_agg_pkey PRIMARY KEY (month_start_date, work_name, unit);


--
-- Name: fact_work_skpdi_report skpdi_report_raw_pkey; Type: CONSTRAINT; Schema: initial_data; Owner: dima_admin
--

ALTER TABLE ONLY initial_data.fact_work_skpdi_report
    ADD CONSTRAINT skpdi_report_raw_pkey PRIMARY KEY (work_report_id);


--
-- Name: idx_plan_agg_description; Type: INDEX; Schema: initial_data; Owner: app_mad_podolsk
--

CREATE INDEX idx_plan_agg_description ON initial_data.fact_work_plan_monthly USING btree (work_name);


--
-- Name: idx_plan_agg_month_desc_unit; Type: INDEX; Schema: initial_data; Owner: app_mad_podolsk
--

CREATE INDEX idx_plan_agg_month_desc_unit ON initial_data.fact_work_plan_monthly USING btree (month_start_date, work_name, unit);


--
-- Name: fact_price_2025 fk_price_desc; Type: FK CONSTRAINT; Schema: initial_data; Owner: dima_admin
--

ALTER TABLE ONLY initial_data.fact_price_2025
    ADD CONSTRAINT fk_price_desc FOREIGN KEY (work_item_id) REFERENCES public.dim_work_item(work_item_id);


--
-- Name: fact_price_2025 fk_price_section; Type: FK CONSTRAINT; Schema: initial_data; Owner: dima_admin
--

ALTER TABLE ONLY initial_data.fact_price_2025
    ADD CONSTRAINT fk_price_section FOREIGN KEY (estimate_section_id) REFERENCES public.dim_estimate_section(estimate_section_id);


--
-- Name: fact_price_2025 fk_price_smeta; Type: FK CONSTRAINT; Schema: initial_data; Owner: dima_admin
--

ALTER TABLE ONLY initial_data.fact_price_2025
    ADD CONSTRAINT fk_price_smeta FOREIGN KEY (estimate_id) REFERENCES public.dim_estimate(estimate_id);


--
-- Name: SCHEMA initial_data; Type: ACL; Schema: -; Owner: dima_admin
--

GRANT USAGE ON SCHEMA initial_data TO app_mad_podolsk;


--
-- Name: TABLE fact_price_2025; Type: ACL; Schema: initial_data; Owner: dima_admin
--

GRANT SELECT ON TABLE initial_data.fact_price_2025 TO app_turnover_u4s;
GRANT ALL ON TABLE initial_data.fact_price_2025 TO app_mad_podolsk;


--
-- Name: TABLE fact_price_2026_upto_may; Type: ACL; Schema: initial_data; Owner: dima_admin
--

GRANT ALL ON TABLE initial_data.fact_price_2026_upto_may TO app_mad_podolsk;
GRANT SELECT ON TABLE initial_data.fact_price_2026_upto_may TO app_turnover_u4s;


--
-- Name: TABLE fact_work_actual_pik; Type: ACL; Schema: initial_data; Owner: dima_admin
--

GRANT SELECT ON TABLE initial_data.fact_work_actual_pik TO app_turnover_u4s;
GRANT ALL ON TABLE initial_data.fact_work_actual_pik TO app_mad_podolsk;


--
-- Name: TABLE fact_work_by_subcontractor; Type: ACL; Schema: initial_data; Owner: dima_admin
--

GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLE initial_data.fact_work_by_subcontractor TO app_mad_podolsk;


--
-- Name: COLUMN fact_work_by_subcontractor.work_report_id; Type: ACL; Schema: initial_data; Owner: dima_admin
--

GRANT INSERT(work_report_id),UPDATE(work_report_id) ON TABLE initial_data.fact_work_by_subcontractor TO dima_admin;


--
-- Name: TABLE fact_work_plan_monthly; Type: ACL; Schema: initial_data; Owner: app_mad_podolsk
--

GRANT SELECT ON TABLE initial_data.fact_work_plan_monthly TO app_turnover_u4s;
GRANT INSERT,DELETE,UPDATE ON TABLE initial_data.fact_work_plan_monthly TO dima_admin;


--
-- Name: TABLE fact_work_skpdi_report; Type: ACL; Schema: initial_data; Owner: dima_admin
--

GRANT SELECT ON TABLE initial_data.fact_work_skpdi_report TO app_turnover_u4s;
GRANT ALL ON TABLE initial_data.fact_work_skpdi_report TO app_mad_podolsk;


--
-- Name: SEQUENCE prices_2025_id_price_seq; Type: ACL; Schema: initial_data; Owner: dima_admin
--

GRANT SELECT ON SEQUENCE initial_data.prices_2025_id_price_seq TO app_turnover_u4s;
GRANT ALL ON SEQUENCE initial_data.prices_2025_id_price_seq TO app_mad_podolsk;


--
-- Name: SEQUENCE prices_2026_uptomay_id_price_seq; Type: ACL; Schema: initial_data; Owner: dima_admin
--

GRANT ALL ON SEQUENCE initial_data.prices_2026_uptomay_id_price_seq TO app_mad_podolsk;
GRANT SELECT ON SEQUENCE initial_data.prices_2026_uptomay_id_price_seq TO app_turnover_u4s;


--
-- Name: TABLE skpdi_report_raw_tmp; Type: ACL; Schema: initial_data; Owner: dima_admin
--

GRANT SELECT ON TABLE initial_data.skpdi_report_raw_tmp TO app_turnover_u4s;
GRANT ALL ON TABLE initial_data.skpdi_report_raw_tmp TO app_mad_podolsk;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: initial_data; Owner: dima_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE dima_admin IN SCHEMA initial_data GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON TABLES TO app_mad_podolsk;


--
-- PostgreSQL database dump complete
--

\unrestrict XNR480mEhH6U41GiDYIggTCfGEY0BBFNNzTwKNAtVfyFJ7oKyVyF2eAenWbjzjP

